# Generated by Django 3.2.12 on 2022-04-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_surname', models.CharField(max_length=30)),
                ('customer_age', models.IntegerField()),
                ('customer_post_code', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('product_brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supermarkets',
            fields=[
                ('supermarket_id', models.AutoField(primary_key=True, serialize=False)),
                ('supermarket_name', models.CharField(max_length=30)),
                ('supermarket_link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_details',
            fields=[
                ('ticket_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(max_length=30)),
                ('article_code', models.IntegerField()),
                ('article_name', models.CharField(max_length=30)),
                ('article_quantity', models.FloatField()),
                ('article_unit_price', models.FloatField()),
                ('article_vat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(max_length=30)),
                ('ticket_date', models.DateField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
