# Generated by Django 3.2.13 on 2022-07-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XPNSES_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
